version: '3.8'

services:
  squadjs:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        npm install -g yarn@1.22.0 &&
        yarn install &&
        node index.js
      "
    environment:
      - NODE_ENV=production
    restart: unless-stopped 